# Generated by Django 6.0.5 on 2026-08-28 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255, verbose_name='Job Title')),
                ('job_role', models.CharField(max_length=255, verbose_name='Job Role/Description')),
                ('skills_required', models.TextField(help_text='Comma-separated list of skills', verbose_name='Required Skills')),
                ('experience_required', models.PositiveIntegerField(default=0, verbose_name='Required Experience (Years)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(blank=True, default='Unknown Candidate', max_length=255)),
                ('resume_file', models.FileField(upload_to='resumes/')),
                ('match_score', models.FloatField(default=0.0, verbose_name='Overall Match Score')),
                ('skills_match_score', models.FloatField(default=0.0, verbose_name='Skills Match Score')),
                ('experience_score', models.FloatField(default=0.0, verbose_name='Experience Score')),
                ('project_score', models.FloatField(default=0.0, verbose_name='Project Analysis Score')),
                ('education_score', models.FloatField(default=0.0, verbose_name='Education Check Score')),
                ('skills_match_details', models.JSONField(blank=True, default=dict)),
                ('experience_details', models.JSONField(blank=True, default=dict)),
                ('project_analysis_details', models.JSONField(blank=True, default=dict)),
                ('education_check_details', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='comparator.jobposting')),
            ],
        ),
    ]
